### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by LvShengZe903** [jerrygaoLondon/RPDNN#1]
when i  run python rumour_dnn_evaluator.py give the no such file or directory error.
![image](https://user-images.githubusercontent.com/51954425/129342572-6cd82cab-ab84-4937-904f-35281b624cb0.png)
I will be very appreciate if you could give me an early reply

**Comment by jerrygaoLondon** [comment]
thanks for your interest. you need to download this model from https://figshare.shef.ac.uk/articles/dataset/Credibility_corpus_fine-tuned_ELMo_contextual_language_model_for_early_rumor_detection_on_social_media/11591775/1 (as we documented in https://github.com/soojihan/Multitask4Veracity) and save the model into the right directory

**Comment by LvShengZe903** [comment]
> thanks for your interest. you need to download this model from https://figshare.shef.ac.uk/articles/dataset/Credibility_corpus_fine-tuned_ELMo_contextual_language_model_for_early_rumor_detection_on_social_media/11591775/1 (as we documented in https://github.com/soojihan/Multitask4Veracity) and save the model into the right directory

Thank you for your reply!
